default:
  tags:
    - docker

stages:
  - test
  - triggers

service_produits:
  stage: triggers
  trigger:
    include: mcommerce-produits/.gitlab-ci.yml
  rules:
    - changes:
      - mcommerce-produits/**/*

service_paiement:
  stage: triggers
  trigger:
    include: mcommerce-paiement/.gitlab-ci.yml
  rules:
    - changes:
      - mcommerce-paiement/**/*

service_commandes:
  stage: triggers
  trigger:
    include: mcommerce-commandes/.gitlab-ci.yml
  rules:
    - changes:
      - mcommerce-commandes/**/*

frontend:
  stage: triggers
  trigger:
    include: mcommerce-frontend/.gitlab-ci.yml
  rules:
    - changes:
      - mcommerce-frontend/**/*

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml